### ISSUE TITLE
Re:Earth public API

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#126]
## User story
By providing operations related to Re:Earth as a public API, users will be able to reference, modify, and delete data in Re:Earth from their own applications.
In this way, users will be able to add data from an external CMS, or use Re:Earth as a CMS, and utilize it as a data platform.

## Requirements
- 
## Testing list
- [ ]

**Comment by lavalse** [comment]
I think users can write a plugin to make it work. And the plugin system is designed for this request. So I will close this issue.
