### ISSUE TITLE
Merged Infobox

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#128]
## Leader
@mimoham24 

## User story
Currently, when an Infobox is set as the parent element, the child elements only have the option of using the Infobox passed from the parent or using a custom Infobox. The user wants to use the Infobox passed from the parent, but also wants to use some of the blocks added by the user. In this case, it is necessary to merge the blocks passed from the parent and the blocks that are maintained by the user.

## Requirements
- There is layer group which is linked with 
## Testing list
- [ ]

**Comment by lavalse** [comment]
This is an issue for Classic. And dev team has already developed this.
