### ISSUE TITLE
Import 3Dtiles as dataset

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#150]
**Is your feature request related to a problem? Please describe.**
3Dtiles is a well-designed data format that can have geospatial data and also buildings. Re:Earth's dataset feature is useful to link a property to the dataset field.
However, since it doesn't support 3Dtiles I cannot import and take full advantage of it.

**Describe the solution you'd like**
Implement the feature to parse and save 3Dtiles as a dataset

**Comment by lavalse** [comment]
It is difficult to allow our Visualizer to upload a 3D tiles zip file. And user should upload the 3D Tiles to CMS, or another server. I think it is ok to close this issue.
