### ISSUE TITLE
Generate 3Dtiles from dataset

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#151]
**Is your feature request related to a problem? Please describe.**
Since 3Dtiles is a well-designed data format for WebGIS I want to create it from data on Re:Earth.

**Describe the solution you'd like**
Users can choose which field is used for which field of 3Dtiles. Then 3Dtiles data will be exported from the selected dataset.

**Comment by lavalse** [comment]
I think it is too difficult for us to do this. The Re:Earth flow is designed to handle this request. I will close this issue.
