### ISSUE TITLE
Linked dataset layer won't pass property values to children if it's inside of other folders

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#156]
**Describe the bug**
The linked dataset layer which has been created from the dataset is able to pass the property values to its children. For example, if the user set altitude, all children should take over it unless they have own value. However, if the linked dataset layer is moved to any folder, this feature doesn't work.

**To Reproduce**
1. Go to the Editor page
2. Import dataset
3. Create a layer group by dragging and dropping it to the earth
4. Set altitude 1000 m
5. Children's altitude will be 1000m and its color will be blue
6. Move layer group inside of another folder
7. Any value won't be passed to children

**Expected behavior**
Even if the linked layer group is under another folder, it should be able to pass the property values to its children

**Comment by lavalse** [comment]
This issue is out of date. So I will close this issue.
