### ISSUE TITLE
Infobox for widget

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#160]
## Leader
@KaWaite 

## User story
Thanks to the Widget Align System user can freely align widgets on WAS. However, there are some widgets that cannot work on the WAS. For example, the button widget shows modal. Splashscreen is also one example.

## Testing list
- [ ]

**Comment by lavalse** [comment]
Plugin support model and popup, so users can use that API to create something similar to Splashscreen. So I will close this issue.
