### ISSUE TITLE
[Dataset update]: add or delete layers when linked dataset schema is updated

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#173]
## Todo 
- When the dataset schema is been updated
	* If the dataset schema is linked to layer group, 
	* If the number of dataset schema fields are
		* increased
			* linkable fields should be added
		* decreased
			* layer property which had been linked should be unlinked(default value of the property will be used)
	* if the number of datasets is 
		* increased
			* Additional layer should be created and also some properties are linked which other layers as are
		* decreased
			* The layer which had been linked to the dataset deleted should be removed from the scene
* If new dataset schema is incompatible with older dataset schema, it should show an error

**Comment by lavalse** [comment]
There is no dataset in the current visualizer system. So this issue is out of date. I will close this.
