### ISSUE TITLE
Tag generated Incorrectly

### ISSUE THREAD

**Issue by arisamikumo** [reearth/reearth-visualizer#188]
**Describe the bug**
## Description
Making tags in Japanese,
1. Tags are generated by pressing Enter to convert text to kanji.
2. The selected text lefts in input field

**To Reproduce**
Make a Tag on Japanese and try to convert to kanji

**Expected behavior**
Tags will generate second press Enter (not First press enter to convert) 

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome
 - Version ?

**Comment by lavalse** [comment]
This issue is out of data. And for visualizer, there is no tag system any more
