### ISSUE TITLE
Tag inheritance

### ISSUE THREAD

**Issue by arisamikumo** [reearth/reearth-visualizer#192]
**Is your feature request related to a problem? Please describe.**
Tag : can set tag to folder(parents) but it not inheritance to marker(child)
Infobox : can set Infobox style to folder(parents) and it inheritance to marker(child)
→it makes users confuse

**Describe the solution you'd like**
Tag should behave same as Infobox or make it impossible that adding tag to folders.

**Comment by lavalse** [comment]
There is no tag system in our new visualizer any more. So I will close this issue.
