### ISSUE TITLE
Dataset architecture refinement

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#208]
## Leader
@rot1024 

## Current problem
Re:Earth was initially developed with the idea of enabling the creation of projects that do not have a large number of data, such as Hiroshima Archives. 

Now, Re:Earth is being developed as a WebGIS platform, and many users are demanding to handle large datasets. However, the current design of Re:Earth is flawed, and when a few hundred data are imported, it makes Re:Earth very slow.

<details>
<summary>**Why does Re:Earth slow down even if the dataset is only a few hundred at most?**</summary>

## **One-to-one correspondence between layers and datasets (records)**
All datasets are also stored as layers; if you have 100 datasets, 100 layers will actually be created. It also means that every time we update the dataset, Re:Earth have to delete and rebuild many layers.

## **The actual display content is calculated each time a request is made to the backend**
The process of calculating the actual display content by multiplying the layer settings with the dataset values is done in the backend, and the only way to get the results is to use GraphQL. Currently, Re:Earth doesn't store cache the result of the calculation every time we change the value of a property.
This also causes the N+1 problem in GraphQL, which sends a huge number of queries to MongoDB (5 queries for 1 record, 500 queries for 100 records). Note that this problem can be partially resolved to introduce data loader.

## A**lways required to copy the entire contents of the dataset to use them in Re:Earth**
Because the layers and datasets are tightly coupled, in order to use data created in CMS in Re:Earth, the entire contents of the dataset must be copied into Re:Earth. This does not allow us to draw a clean system boundary between CMS and Re:Earth.

## **GraphQL and JSON are not efficient for large and GIS data**
It is not possible to adopt a binary format to increase the efficiency of dataset transfer. GraphQL is JSON, so binary data cannot be included in the payload, and parsing JSON is not efficient. Also, as the best data formats evolve with the times, we need to be able to easily migrate to them in the future. Also, resolvers in GraphQL can cause N+1 problems if not implemented with care.

## **Rarely do users want to overwrite the contents of a dataset layer individually**
In GIS, users often want to apply the same style to the entire dataset (the "formula" applied to the values is the same even when coloring polygons) or change the look of at most a few datasets. Because of this, there is no point in creating a one-to-one correspondence between layers and datasets at the expense of performance.

## Very complex implementation causes bugs
Merging properties and datasets is done both in the front-end and in the back-end, and the implementation gets bloated, especially in the back-end. This reduces maintainability and development agility, and is a major cause of bugs. Also when a new engineer comes in, it is very hard for him/her to understand the implementation.
</details>

## 1. New dataset API via HTTP REST API (No breaking changes)

Instead of GraphQL, large datasets are delivered in more efficient format and via a new HTTP REST API. This method is more compatible with CDNs and easier to tune for performance. It is also possible to deliver the data in a more efficient data format for some usecases if necessary.

- Attribute data (including points)
    - `GET /datasets/{id}.json` : Attributes in JSON
    - `GET /datasets/{id}.csv` : Attributes in CSV (for external services)
    - `GET /datasets/{id}.msgpack` : Attributes in MessagePack
    - ???: A binary format that is suitable for GPU shaders
    - ...
- Geometry data (points, polylines and polygons)
    - `GET /datasets/{id}.fgb`: Geometry data as **FlatGeobuf** (should support Range header)
    - `GET /datasets/{id}.geojson` : Geometry data as GeoJSON
    - `GET /datasets/{id}.topojson` : Geometry data as TopoJSON
    - ...

Note that metadata of datasets are still available in GraphQL.

These APIs are called by frontend. When the scene is loaded, the first thing to do is to get the layer and property information. If the scene is in the editor, it is retrieved from GraphQL, and if it is an exported scene, it is retrieved from the JSON file. This will determine the dataset required for display. At that point, the frontend makes a request to the dataset API. If the dataset is used but the layer is hidden, it is also possible to delay the dataset retrieval until the first time the layer is shown.

<details>
<summary>**Why does it work well?**</summary>

### Why separating APIs between attribute data and geometry data?

While GIS data has a format suitable for GIS data, Re:Earth will need to handle various data such as time series data in the future, and there is currently no format that can efficiently encode and store such information. 
So, as long as Re:Earth has the APIs and encoders of various formats, changing the data format is easy: just change the URL extension. if the extension is `.msgpack`, information about attributes will be delivered as MessagePack, and if the extension is `.fgb`, geological data will be delivered. Attributes and geographic features are associated by record IDs. With this approach, the expressiveness of attribute data is not limited by the GIS format. 

### Deliver datasets as-is to external services
Since the API is a very ordinary HTTP REST API, it can be easily integrated with many existing systems by simply setting the public scope of the dataset and allowing access to the dataset without authentication. Authentication is OIDC compliant, so it is easy to integrate with existing systems even if authentication is required. Of course, data distribution using public API keys can also be realized.

### Caching and compatibility with CDN
The first time a dataset is requested through the API, it will be encoded into the respective data format. Caching is the responsibility of the CDN, but GCP does not allow CDNs to be authenticated, so we can either use a different CDN, or the backend can cache it on its own, or we don't have to cache it if the cost of encoding is not too high.
</details>

## Requirements
- 
## Testing list
- [ ]

## Reference
![image](https://user-images.githubusercontent.com/49897538/151273090-06236ce0-7097-40e0-bf3b-faa36960f0ec.png)

**Comment by lavalse** [comment]
The New Layer System makes this architecture come true. I will close this issue.
