### ISSUE TITLE
selectable ClassificationType

### ISSUE THREAD

**Issue by nbayashi** [reearth/reearth-visualizer#216]
**Is your feature request related to a problem? Please describe.**
When drawing geojson polygons and 3Dtyles, the building is filled with the color of the polygon.
If possible, the buildings should not be filled in.

**Describe the solution you'd like**
Add geojson polygons and 3Dtyles
the building is filled with the color of the polygon.

**Describe alternatives you've considered**
I can select ClassificationType to BOTH or TERRAIN.

**Additional context**
![image](https://user-images.githubusercontent.com/13118515/152107779-2b1d18d9-2d85-44c3-9de9-b3faf71949f1.png)

**Comment by lavalse** [comment]
Users can choose ClassificationType on the style editor panel. 
![image](https://github.com/user-attachments/assets/626f3f02-46a2-4493-bf23-778b1ccbd089)
So I think the issue has been solved. I will close this issue.
