### ISSUE TITLE
Front-end E2E test 

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#26]
## Test list
- [ ] Login
- [ ] Create a project
- [ ] Select a project
- [ ] Earth Editor
   - [ ] create layer
   - [ ] add layer
   - [ ] create folder
   - [ ] delete layer
   - [ ] select layer
   - [ ] change layer's order
   - [ ] open the folder
   - [ ] rename layer
   - [ ] invisible layer
   - [ ] create infobox
   - [ ] change property value
      - [ ] text
      - [ ] drop down
      - [ ] color picker
      - [ ] camera
      - [ ] 
   - [ ] create block
   - [ ] delete block
   - [ ] export layer
   - [ ] widgets
   - [ ] publish

**Comment by lavalse** [comment]
This issue is out of date. And we will manage E2E test on notion page.
