### ISSUE TITLE
Pedestrian mode

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#288]
## User story
The user wants to operate and view the map from a pedestrian's perspective on a three-dimensional map. This way, they can not only get a bird's eye view, but also see how the area looks from an actual person's perspective. For example, it can be used to preview 3D building data or to simulate urban development.

## Requirements
- User can toggle pedestrian mode
- User can choose the location to start the mode
- User can mode with keyboard shortcut
- The mini-map should be displayed
- The image which tells us how to use the mode should be shown
- 
If you have any other ideas to improve the feature, welcome!

## Examples
[This](https://plateauview.mlit.go.jp/) is the example that we want to have.

![スクリーンショット 2022-05-18 11 41 21](https://user-images.githubusercontent.com/49897538/168946661-90beeada-73c4-42b4-b5cc-125b12532f6f.png)

![スクリーンショット 2022-05-18 11 41 33](https://user-images.githubusercontent.com/49897538/168946667-35782593-fbe5-472d-bc5d-ee1a86b5ff8e.png)
## Testing list
- [ ]

**Comment by lavalse** [comment]
We already have a [plugin](https://marketplace.reearth.io/plugins/reearth-plugin-pedestrian) which makes this come true.
