### ISSUE TITLE
Getting started in developing custom layers

### ISSUE THREAD

**Issue by gsutay** [reearth/reearth-visualizer#315]
### Discussed in https://github.com/reearth/reearth/discussions/314

<div type='discussions-op-text'>

<sup>Originally posted by **gsutay** August  5, 2022</sup>
Hi Team,

My goal to to setup the needed development environment to be able to create custom layers on top of the 2D/3D WebGIS map.  I assume that I will need to use an API plugin to pull in data from a database to populate the custom layer.

Are my assumptions correct thus far?

To begin setting up a dev env, I have a RHEL server where I opened ports 8080 and 27017 and then have successfully run:

curl -O https://raw.githubusercontent.com/reearth/reearth/main/docker-compose.yml
docker compose up -d

The result is that I can open URL http://localhost:8080/ in Firefox and see a Re:Earth login page.

It is not clear now what user/password to login with.   I have attempted the "Sign up" to created a new user and I get the message "_Please check your inbox for instructions on how to verify your account._"  However, I never receive the email.  I am stuck.  I cannot get past the login page on http://localhost:8080/.  Is there a way to manually create the login? 

I will attempt to find the Auth0 config in the docker image and see if introducing a user/pass there will get me past the login page.

UPDATE 1:
I can get into the mongo:4.4-focal container using 'docker exec -ti 8f97cc041a0f "bash"' but I don't see any Auth0 config there to tweak.

Trying various commands and permutations to 'docker exec -ti ...' into the reearth/reearth:latest container all fail.

UPDATE 2:
On page "https://docs.reearth.io/developer-guide/intro/setup/auth0", I see text "In previous versions of Re:Earth, Auth0 configuration was required, but the current version has a built-in authentication server, so it works without Auth0 configuration."

This suggests that there are built-in user/pass to get past the login page already in the docker image. Could somebody please share the default user/pass configured to work on the "built-in authentication server" please?

Cheers,
Gene</div>

**Comment by lavalse** [comment]
Hey. Sorry to make the system different to use. But now we support a mock system on local environment to let user use our system without login. Pls, check our docs in the future.
