### ISSUE TITLE
Auto start of story telling doesn’t work.

### ISSUE THREAD

**Issue by nbayashi** [reearth/reearth-visualizer#371]
**Describe the bug**
Auto start of story telling doesn’t work.

**To Reproduce**
Add story telling widget.
Turn on “auto start” toggle.
add story list.
View published page or preview page.
But now, although it select first story layer, didn’t zoom to.
Or was it a spec that it didn’t zoom?

**Expected behavior**
 it must be selected and zoom to first story layer when view published page or preview page.

**Screenshots**
![storytellingbug](https://user-images.githubusercontent.com/13118515/202600205-fc41a5b3-f7a9-45dc-8be6-75a8e62b6443.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chorme

**Additional context**
Reported by Chunichi Shimbun.

**Comment by lavalse** [comment]
This issue has been solved. So I will close this issue.
