### ISSUE TITLE
Plugin API to get query parameters

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#372]
## Leader
@airslice 

## User story
Plug-in developers would like to be able to receive the values of query parameters in the URL. This will allow the developer to add arbitrary query parameters to the published page and change the initial values or behavior of the plugin according to those values.

## Requirements
Develop plugin API
* `reearth.viewport.query: Record<string, string>`

## Testing list
- [ ]

**Comment by lavalse** [comment]
This issue has been developed. I will close this issue.
