### ISSUE TITLE
Export a scene as a set of HTML/CSS/JS

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#5]
## User story

Users want to export the scene as a set of HTML/CSS/JS (we can see the archive with self-hosting), that is why users can host their own archives even if app.reearth.io does no longer live.

## Acceptance criteria

- Can export without collapse
- If you deploy exported files, the site works

## Completion condition

- [ ] All PRs were passed CI, code-reviewed, and merged
- [ ] Tested on staging env
- [ ] A demonstration was held

## Note

**Comment by lavalse** [comment]
This issue is out of date. Let's close this issue
