### ISSUE TITLE
Enable to use web font

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth-visualizer#55]
## Leader
@issmail-basel 

## User story
Users currently only have a choice of fonts from Re:Earth, and would like to use their own Webfont with Infobox, Label, etc. We would like to use unique web fonts for Infobox, Label, etc. This will give us a wider range of design option

## Requirements
* Can input webfont URL or JS code
* The fonts which are added by users can be chosen from the fonts pull-down list
* Web font works on published page as well
- [ ] write document
   - [ ] Front-end
   - [ ] [Back-end](#217 )

**Comment by lavalse** [comment]
This issue is out of date. I will close it.
