### ISSUE TITLE
Create slides in the infobox

### ISSUE THREAD

**Issue by kk-kkch03** [reearth/reearth-visualizer#586]
**Is your feature request related to a problem? Please describe.**
Slides that make storytelling engaging cannot be created within Re:Earth.

ストーリーテリングを彩るスライドをRe:Earth内で作成できない。

**Describe the solution you'd like**
Extend the functionality of the infobox to allow the creation of slides.

Example

- Allow character-by-character formatting
- line spacing
- Download created slides

インフォボックスの機能を拡張し、スライドを作成できるようにする。

例

- 一文字ごとの書式設定
- 行間設定
- 作成したスライドのダウンロード

**Describe alternatives you've considered**
A possible alternative would be to add a plug-in to display slides created by other services.

代替案として考えられるのは、他のサービスで作成されたスライドを表示するプラグインを追加することが考えられる。

**Additional context**
The most effective way is to display downloaded images in a photo overlay, but it is tedious to start over from scratch every time a change is made.

最も効果的な方法は、ダウンロードした画像をフォトオーバーレイで表示することだが、変更のたびに最初からやり直すのは面倒だ。

<img width="1437" alt="スクリーンショット 2023-07-23 15 42 15" src="https://github.com/reearth/reearth/assets/72206552/b34c7ffa-3e47-4306-8024-c6d96af2e390">

Graphic Recording
![無題18_20230723165345](https://github.com/reearth/reearth/assets/72206552/670e9d26-79f4-4395-a117-2ddae3cf8c68)

**Comment by lavalse** [comment]
Our new Visuliazer has a nice story telling system which works like a slider. please try it. I will close this issue. Thank you very much.
