### ISSUE TITLE
マーカー機能でポイントした位置とマーカーの表示位置が地図の表示場所移動時にずれる。Marks move from the positions pointed by the marker function when  the position is moved

### ISSUE THREAD

**Issue by Toshiharu-Matsuura** [reearth/reearth-visualizer#593]
バグ内容
マーカー機能でポイントした位置とマーカーの表示位置が地図の表示場所を移動した際にずれてしまう。
Marks move from the positions pointed by the marker function when the position is shifted.

**再現手順  to reproduce**

1. マーカー機能でポイント  pointing a spot  by the marker function
2.ドラッグアンドドロップで地図の表示位置を変更  Change the display position on the map by drag and drop.
3. マーカーがそのスポットからずれずに移動する  A marker stays on the spotted position when the map is shifted.  
**graphic re
<img width="1440" alt="スクリーンショット 2023-07-27 22 58 14" src="https://github.com/reearth/reearth/assets/139119383/fd6f9a91-03c0-4232-98e6-d61f092a4186">
cording**

**Screenshots**
<img width="1433" alt="スクリーンショット 2023-07-27 20 17 28" src="https://github.com/reearth/reearth/assets/139119383/cc698208-bc0d-4cb2-b95e-f8254afd0b0b">

**Desktop (please complete the following information):**
 - OS: [mac OS ventura]
 - Browser [Chrome]
 - Version [13.4.1(c)]

**Comment by lavalse** [comment]
The reason why this happens is because the terrain is enabled. It is our mistake, but I think this issue has been solved by our new Visualizer application. Pls, have a try if having a chance.
