### ISSUE TITLE
PLATEAUの3D建物モデルを入れた際、マーカーの高さを建物の高さに位置できるようにしてほしい

### ISSUE THREAD

**Issue by Yosi0530** [reearth/reearth-visualizer#607]
## PLATEAUの3D建物モデルをインポートし、その後マーカーを追加すると建物にマーカーが埋もれて見えなくなってしまい、ユーザー側がマーカーの高さを探り探りで設定しなければならなくなり、手間がかかってしまう。

Importing PLATEAU's 3D building model and then adding markers would be time-consuming because the markers would be buried in the building and would not be visible, and the user would have to explore and set the height of the markers.

![359886796_1250135918997852_6839056997499395765_n](https://github.com/reearth/reearth/assets/93134160/15056216-2231-415d-b4b3-9c0eaa7dd6e5)

## Requirements
* PLATEAUの3D建物モデルをインポートし、マーカーの「レイヤー」の欄に座標もしくは建物名を入力した際、その建物の高さに合わせた高さ位置のマーカーが出るようにしてほしい。
 When importing a 3D building model from PLATEAU and entering the coordinates or building name in the "Layer" field of the marker, I would like the marker to appear at a height position that matches the height of the building.
* そのため、マーカーの「レイヤー」の欄に建物名を検索する欄も追加してほしい。
For this reason, we would also like to see a field added to the "layers" section of the marker to search for building names.

## Examples
![363706225_214062227923683_8863750161357269066_n](https://github.com/reearth/reearth/assets/93134160/0a6d160a-d343-4382-b9b6-7b88a010e67a)

## グラレコ
![359675005_751997973347315_333033483162073594_n](https://github.com/reearth/reearth/assets/93134160/aa3459fa-2533-4515-965c-75fab6cf16a5)

**Comment by lavalse** [comment]
It is very difficult to let Re:Earth support. Because Re:Earth not only supports Plateau 3D Tiles, but also all other data. I think if some engineer can develop a plugin that maybe can make your idea come true.
