### ISSUE TITLE
建物にピンを指すときの曖昧さについて

### ISSUE THREAD

**Issue by an88ri** [reearth/reearth-visualizer#608]
建物にピンをするときに、例えば団地や学校などの土地範囲が広い場合、ピンを指すところを決めずらいのでその土地自体を一建物として認識できる機能があればいいと思いました。When pinning on a building, for example, in multi-unit apartments
 or a school, it is difficult to decide where to pin on a large area of land.So I thought it would be good to have the ability to recognize large lot as a single building.
![2023-07-31](https://github.com/reearth/reearth/assets/139886325/41d0b8ca-bb58-46d9-b528-c25a2ee75db5)
![2023-07-31 (1)](https://github.com/reearth/reearth/assets/139886325/fcada0dd-b221-4205-9a21-ba6885e0564f)
![S__51060772](https://github.com/reearth/reearth/assets/139886325/cc066d93-583e-4dcc-b400-f7605868edef)

**Comment by lavalse** [comment]
The new visualizer supports drawing polygons and polylines, which can solve this request. Thank you very much.
