### ISSUE TITLE
PLATEUの３Dモデルを入れた際に生じるバグを改善してほしい

### ISSUE THREAD

**Issue by minaitani** [reearth/reearth-visualizer#609]
PLATEUの３Dモデルをリアースに持ってきた際に、３Dモデルが上下逆さまになってしまうというバグが生じた。何か設定を押さなけれならなかったのかもしれないが、１つのボタンを押したら、バグもなくそのまま３Dモデルが入るようにしてほしい。

When bringing a 3D model from PLATEU to the rears, a bug occurred where the 3D model was upside down. Perhaps some setting had to be pressed, but I would like to see the 3D model go in as is without any bugs when one button is pressed.

![image](https://github.com/reearth/reearth/assets/139448677/0b5c50eb-3a03-4bd7-8366-3c2741488e20)

![image](https://github.com/reearth/reearth/assets/139448677/5d4d1f7e-e153-484f-9575-26c690b05a3c)

**Comment by lavalse** [comment]
多分この問題は今ないので、Closeしましょう。
