### ISSUE TITLE
Map tile slider

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth-visualizer#74]
## User story
Currently, multiple tile maps can be registered. The user wants to display different tiles depending on the Zoom level. To do so, the user needs to set the Max and Min Zoom levels, but the existing UI doesn't know what the current Zoom level is and what values should be set for Max and Min. By implementing a map tile slider, we can know the current zoom level and see where the tilemap will be displayed.

## Requirements
* Can set min, max by slider
* Can see current zoom level
* Can see the actual value
* Can change the camera zoom level by slider
## Completion condition

- [ ] All PRs were passed CI, code-reviewed and merged
- [ ] Tested on staging env
- [ ] Released in the production env
- [ ] A demonstration was held

**Comment by lavalse** [comment]
This has been done. So I will close this issue.
