### ISSUE TITLE
Enhance Shapefile support

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth-visualizer#77]
## User story
When the user tries to download the layer as a shapefile, `shp` extension file will be downloaded. 
To use it on other platforms it should be downloaded with other files like `dbf`

## Acceptance criteria

- [ ] can be downloaded as `zip` file
- [ ] can be opened with QGIS

## Completion condition

- [ ] All PRs were passed CI, code-reviewed, and merged
- [ ] Tested on staging env
- [ ] Released in the production env
- [ ] A demonstration was held

**Comment by lavalse** [comment]
Already support Shape file on API. Need UI support yet. But I will close this issue. It is out of date.
