### ISSUE TITLE
Build E2E test flow for backend 

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth-visualizer#81]
##  User story

Build E2E test flow for reearth-backend to detect degradations.

##  Completion condition

- [ ] All PRs were passed CI, code-reviewed, and merged
- [ ] E2E test is working as expected, confirmed by @rot1024

**Comment by rot1024** [comment]
## Current concept

- E2E tests are different from unit tests, so we will create a separate build like `cmd/reearth-e2e/main.go`.
- Initialize a GraphQL resolver and send requests to it by calling functions. There is no need to set up a server.
- **Separate database name and file path to save uploaded files** for test and production
- Drop the database (including files) before starting E2E test
- The test cases are written in a `/test/*.graphql` file and the expected responses are written in a `.json` file of the same name.
- Just by adding more files, the number of test cases will increase by itself.

## Research

- How do you do backend E2E testing for other GraphQL adoption projects? (Not limited to Go) (I want to reinvent the wheel as little as possible)

**Comment by lavalse** [comment]
This issue is out if date. I will close it.
