### ISSUE TITLE
Exported CZML's id field is blank

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#90]
**Describe the bug**
When the layer is exported as a CZML file, its id is blank.

**To Reproduce**
1. Go to Earth editor
2. Add a layer
3. Click "Export" tab
4. choose "CZML" file type
5. Export it
6. Open the file

**Expected behavior**
The layer should be exported as CZML file without id field

**Comment by lavalse** [comment]
This issue is out of date. So I will close this.
