### ISSUE TITLE
KML file exported linked layer group is empty

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth-visualizer#91]
**Describe the bug**
KML file exported linked layer group is empty

**To Reproduce**
1. Go to Earth editor
2. Add dataset
3. Drag and drop dataset to the earth
4. Click linked layer group
5. click the "Export" tab
6. Choose "KML" as file type
7. Export it
8. The file is empty

**Expected behavior**
The KML file shouldn't be empty

**Comment by lavalse** [comment]
This issue is out of date. So I will close it.
